##订单服务的端口号
server:
  port: 8004
##服务别名---服务注册到注册中心的名称
spring:
  application:
    name: order-server
  ##数据库连接信息
  datasource:
    name: wechat-shop-order
    url: jdbc:mysql://127.0.0.1:3307/wechat-shop-order?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      ##当前会员服务注册到eureka服务的地址
      defaultZone: http://localhost:8100/eureka/,http://localhost:8200/eureka/
    ##需要将服务注册到注册中心
    register-with-eureka: true
    ##需要检索服务
    fetch-registry: true