##商品服务的端口号
server:
  port: 8002
##服务别名---服务注册到注册中心的名称
spring:
  application:
    name: commodity-server
  ##数据库连接信息
  datasource:
    name: wechat-shop-commodity
    url: jdbc:mysql://127.0.0.1:3307/wechat-shop-commodity?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ##es服务器地址 超时时间
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
      properties:
        transport:
          tcp:
            connect_timeout: 120s
eureka:
  client:
    service-url:
      ##当前商品服务注册到eureka服务的地址
      defaultZone: http://127.0.0.1:8100/eureka/,http://127.0.0.1:9100/eureka/
    ##需要将服务注册到注册中心
    register-with-eureka: true
    ##需要检索服务
    fetch-registry: true